version: '2'

services:
  roffice_vpn:
    build:
      context: .
      dockerfile: ./etc/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - EASYRSA_KEY_SIZE=4096
    volumes:
      - ./var/openvpn/:/etc/openvpn
    ports:
      - 1194:1194/udp
    tty: true
    stdin_open: true
    restart: always
